version: 2

config:
  appium:
    server: localhost
    caps:
      platformName: ios
      app: com.example.app

  report:
    skip:
      - Simple
  
  visualizer:
     enabled: false 

tests:
  Some app with 2phase:
    - obfuscator:
        name: ixguard
        application: sample/standard/input
        config: sample/standard/ixguard.yml
    - appium:
        test: tests/appium_test.py
    - autoconf:
    - obfuscator:
        name: ixguard
    - appium:
        test: tests/appium_test.py
  
  Simple:
    - obfuscator:
        name: ixguard
        application: some/app.ipa
        config: some/config.yml
    - appium:
        test: tests/appium_test.py

  Python:
    - python:
        test: tests/python_test.py
  
  SimpleTwo:
    - obfuscator:
        name: ixguard
        application: some/app.ipa
        config: some/config.yml
    - appium:
        test: tests/appium_test.py
        application_id: some.other.app
