version: 2

# Global configuration that is test-independent.
# Can be used to toggle features, setup connection information, and similar.
config:
  appium:
    server: localhost
    caps:
      platformName: ios
      app: com.example.app

  report:
    skip:
      - Simple
  
  visualizer:
     enabled: false 

tests:
  Some app with 2phase:
    # Config defines common values for all stages of a type for this test.
    config:
      appium: 
        application_id: some.company.app
        test: tests/appium_test.py
      obfuscator:
        name: ixguard
    # The actual pipeline defines the order in which stages are called.
    # Any configuration provided here overrides the stage config.
    pipe:
      - obfuscator:
          application: sample/standard/input
          config: sample/standard/ixguard.yml
      - appium:
      - autoconf:
      - obfuscator:
      - appium:
  
  Simple:
    pipe:
      - obfuscator:
          name: ixguard
          application: some/app.ipa
          config: some/config.yml
      - appium:
          test: tests/appium_test.py

  Python:
    pipe:
      - python:
          test: tests/python_test.py
  
  SimpleTwo:
    pipe:
      - obfuscator:
          name: ixguard
          application: some/app.ipa
          config: some/config.yml
      - appium:
          test: tests/appium_test.py
          application_id: some.other.app
